### ISSUE TITLE
Vagrant install not working

### ISSUE THREAD

**Issue by artoog2** [seomoz/dragnet#57] opened 2018-02-14 00:01 UTC
I followed the vagrant install instructions see the install log, there are some compile warnings. See [vagrant.log](https://github.com/seomoz/dragnet/files/1722135/vagrant.log)

Then when I try to run the example code as is, it doesn't import the names.

```
vagrant@dragnet:/vagrant/dragnet-test$ python dg-load.py 
Traceback (most recent call last):
  File "dg-load.py", line 2, in <module>
    from dragnet import content_extractor, content_comments_extractor
ImportError: cannot import name content_extractor


vagrant@dragnet:/vagrant/dragnet-test$ python
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dragnet
>>> dir(dragnet)
['Blockifier', 'BlockifyError', 'Extractor', 'PartialBlock', '_LOADED_MODELS', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', 'blocks', 'compat', 'extract_comments', 'extract_content', 'extract_content_and_comments', 'extractor', 'features', 'load_pickled_model', 'util']
>>> 
```

Did something change in the recent commits? Or maybe I'm doing something wrong..

**Comment by b4hand** [comment] 2018-02-14 01:35
Example code issue is a duplicate of #55 which contains a workaround. I'm guessing that will be fixed shortly. None of the build warnings that you list appear to be an issue.

**Closed by b4hand** 2018-02-14 01:35 UTC
