### ISSUE TITLE
How to install dragnet

### ISSUE THREAD

**Issue by gvola** [seomoz/dragnet#46] opened 2017-02-08 08:49 UTC
Hello. I'm new to python and I found the installation of the package very hard.
Which version do I need ?
Which packages do I need to install ?
It's very complicated for a beginner.
Thanks

**Comment by b4hand** [comment] 2017-02-08 17:31
Duplicate of #43. Please don't open multiple tickets. This is your third ticket created for installation help, and you appear to have not followed the instructions in the README.

**Closed by b4hand** 2017-02-08 17:31 UTC
